// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZpLYUSfIumvAiWsYaxNICqXZw_ZrGQM',
    appId: '1:124582816919:web:b78ea776176d3e1c08cdd2',
    messagingSenderId: '124582816919',
    projectId: 'mynote-4b753',
    authDomain: 'mynote-4b753.firebaseapp.com',
    storageBucket: 'mynote-4b753.appspot.com',
    measurementId: 'G-RH86ZG79KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsOvUhOIF_F8f8qRoP9Qx5dMUGEPu-RGs',
    appId: '1:124582816919:android:ad0f9eb3aa8d4e6208cdd2',
    messagingSenderId: '124582816919',
    projectId: 'mynote-4b753',
    storageBucket: 'mynote-4b753.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEvbKNYKX5CEQcninh9mbQKq-egpoybsg',
    appId: '1:124582816919:ios:a304cce360a7fb6208cdd2',
    messagingSenderId: '124582816919',
    projectId: 'mynote-4b753',
    storageBucket: 'mynote-4b753.appspot.com',
    iosClientId: '124582816919-g0g0pcm17u00tatvh3772o9hpobq4jnt.apps.googleusercontent.com',
    iosBundleId: 'com.abdulrahman.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEvbKNYKX5CEQcninh9mbQKq-egpoybsg',
    appId: '1:124582816919:ios:b64dc138ca269de708cdd2',
    messagingSenderId: '124582816919',
    projectId: 'mynote-4b753',
    storageBucket: 'mynote-4b753.appspot.com',
    iosClientId: '124582816919-ds8ivtp3ecvhmgvkgqggsi0ou7ncfjic.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynote',
  );
}
